source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'shensuo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  
  # 网络框架
  # pod 'Alamofire'
  pod 'Moya', '~> 14.0' # 基于 Alamofire
  
  # JSON 框架
  pod 'KakaJSON', '~> 1.1.2'
  pod 'SwiftyJSON', '~> 4.0'
  
  # 自动布局
  pod 'SnapKit', '~> 5.0.0'
  pod 'Masonry'
  
  # 网络图片框架，
  #  KF.url(url)
  #  .placeholder(placeholderImage)
  #  .setProcessor(processor)
  #  .loadDiskFileSynchronously()
  #  .cacheMemoryOnly()
  #  .fade(duration: 0.25)
  #  .lowDataModeSource(.network(lowResolutionURL))
  #  .onProgress { receivedSize, totalSize in  }
  #  .onSuccess { result in  }
  #  .onFailure { error in }
  #  .set(to: imageView)
  pod 'Kingfisher', '~> 6.0'
  
  # 提示框
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'NVActivityIndicatorView'
  
  # 富文本
  pod 'TextAttributes'
  
  # 响应式编程
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'ReactiveSwift', '~> 6.1'
  pod 'ReactiveCocoa'
  
  # 底部拦
  pod "ESTabBarController-swift"
  
  # 权限申请
  pod 'Permission/Camera'
  pod 'Permission/Notifications'
  
  # 图片选择器
  pod 'ImagePicker'
  pod 'HEPhotoPicker'
  
  pod 'ZLPhotoBrowser'
  # swift图片浏览器
  pod 'JXPhotoBrowser'
  
  # 颜色 UIColor(hex: "#ffafc2")
  # 渐变：[UIColor.blackColor(), UIColor.orangeColor()].gradient()
  pod 'Hue'
  
  # 快速使用userdefault
  # 例子：
  # Defaults[key: colorKey] = "red"
  # Defaults[key: colorKey]
  pod 'SwiftyUserDefaults', '~> 5.0'
  
  # 轮播图
  pod 'LLCycleScrollView'
  
  # 多标签页面
  pod 'JXSegmentedView'
  pod 'JXPagingView/Paging'
  
  # 流式布局
  pod 'TangramKit'
  pod "CollectionKit"
  
  # 强有力的LOG
  # 例子：
  #   let Log = Logger()
  #
  #  Log.trace("Called!!!")
  #  Log.debug("Who is self:", self)
  #  Log.info(some, objects, here)
  #  Log.warning(one, two, three, separator: " - ")
  #  Log.error(error, terminator: "😱😱😱\n")
  pod 'Log'
  
  # 富文本-YYText的swift版本
  pod 'BSText'
  
  # 弹出框
  pod 'SCLAlertView'
  
  # SVGA动图
  pod 'SVGAPlayer'
   
  # bug收集
  pod 'Bugly'
  
  # 高德地图
  pod 'AMapLocation-NO-IDFA'
  
  # 极光
  pod 'JCore', '2.1.4-noidfa'
  pod 'JPush', '3.2.6'          # 推送
  pod 'JAnalytics'              # 统计分析
  pod 'JShare', '1.8.1'         # 分享
  
  # 阿里云 存储OSS
  pod 'AliyunOSSiOS'
  
  # 视频播放器
  pod 'BMPlayer', '~> 1.3.0'
  
  # 动态详情播放器
  pod "Player", "~> 0.13.2"

  # MJ 刷新
  pod 'MJRefresh'

  # 微信SDK
  pod 'WechatOpenSDK'

  # 智能键盘
  pod 'IQKeyboardManagerSwift', '6.3.0'

  # HUD进度显示
  pod 'MBProgressHUD', '~> 1.2.0'
  
  # 二维码
  pod 'swiftScan', :git => 'https://github.com/MxABC/swiftScan.git'

  # 神策分析sdk
  pod 'SensorsAnalyticsSDK'

  # 集成最新版SDK: 本机号码一键登录
  pod 'NTESQuickPass'

  # 高德地图
  pod 'AMapSearch-NO-IDFA'
  
  # 内购工具
  pod 'SwiftyStoreKit'
  
end
